apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: carts
  name: carts
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: carts
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: carts
    spec:
      containers:
        - args:
            - sh
            - -c
            - sleep 30 && /usr/local/bin/java.sh -Djava.security.egd=file:/dev/urandom -jar ./app.jar --port=80
          env:
            - name: JAVA_OPTS
              value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
          image: weaveworksdemos/carts:0.4.8
          name: carts
          ports:
            - containerPort: 80
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
      hostname: carts
      restartPolicy: Always
status: {}
